language: node_js
node_js:
- '6'
script:
- npm test
deploy:
  access_key_id: AKIAIG5K6XQOZJOHOH5A
  secret_access_key:
    secure: CWcfNkaPK2PDF63rHuRGV5eAZlazkAvCgFuObpRYX5fjLGOd0iSD2GiuhwmPJ3pxLUjMbvutIP2tyi2HM8OwLLfunu2i2FiVKmXZL5D93K/CkiUiHYz3QBAAGyPzl7LIGCosVyftAstrNJoGxq6SmmszXGQWjVQTDx5wEGrD5IF6LPu3Cj02qnVN0Tpz2oJCJOnrdB3iWl+C1c6phtn5053sC1+tds48w6NdzxncfnRyN0/5taWttRHBdtIGeKVi46qMCXzEAFsTX1IqKT3XthEgjPHr9BYe0ZBrkzbJduhbKBGielTPGdORmuLra5gNX1kZZNJt1MZq2AaGVwm7dLmP/wb002i706NHPJMh1XFpp5Y23lreps4goFM0ehCgK0fWKcJx6d3mNsNs97jvz81UI/PK/vynnr4ub+VDzRhyb8ledy1faTLsIsbJKy/LK+h7SuaTl+GWJ5Jv/7/pMJB1EOpn41eft18WzqPRqcyJ+C/Yiegj9XZ2WV7WU6LTL+nwKWA2z5v98dVl4nBp+7a0/+JxTRnS1PbTZ8HqeKBceW7EpN55nlHC9fugAcWkYEilPusm7Y89eNeYjs/xbILQOGibB8q+VtZ0WBmEt+DKJdgDWokUcwPTD/i/huoztjO4Vzj+3VtqtUdcLn12BIRquHiIalQrPJCB2Rx3onI=
  provider: lambda
  role: arn:aws:iam::287158525228:role/lambda_basic_execution
  function_name: myFactSkill
  handler_name: index.handler
  runtime: nodejs4.3
notifications:
  email: false
  slack:
    secure: siyEUk8Rlra5qpyOwIyjpkawbxUV8sxg4pkJDCXRjiTH5H4kJnDtEEJtkKrYI/WVZcBhEQo9uVG5Il9ITgD3fcYQwZxmPZ9wDXillM56VHU3Y3XDSgdzfaSs0IhTc5JcG0Jm/17oHRQ4OsfZuKVql4gPgysid4nlnFzoFJF5JZNPPoeFylQUWSS412FXXTq0JMww9L2y0NWJaUuq6dC8N4gAE/zyfAW0+JInDdLu+Nidepxe9ZqV9/tdAibl+CCWGfrxtjp6QDITlSNET0ezRdVqy7l7b+DOY/ZxV8VXUiv9k5R53EWwfp687FXqwZWpaSaE7AD9X38SJBQMxMEBYYGeFVzuTnwOILf4E/m4aeXJ8CuHhwO5HLTVHxT9DBl9tNrpM53RVFkeRiGikaV8yKicMGxIueaZ+KyhvHf9NBInU9fyqieaBq8boL/00u4I6wG26lLLYpHCdCE7HRNdk1rgMP3sWDqHVONSCJdu1PQUWs0VpBMvKXiauVsl80eP3N6ErKopY5TVsu4n9o7aqYyRfPiBbflH3zV74XBBtkvoh5gUe7ZhJxN3Rn9hDZnhQh/uQZLOVw4XyI934E5n1/KgGQSHW+uBM1W1OSB7fw/9EIl2zXKwL3hXNWNDhl1TRALcIudMFNAB9vRd2rUEgjXxUdPjatVuG6Psz6BenAQ=
