language: node_js
node_js:
- '6'
script:
- npm test
deploy:
  access_key_id: AKIAIABFGVTFAI2EFQ5A
  secret_access_key:
    secure: aShVIj0umHugYRUZqI+B2cxkS1F6DXRscX8EiQ3nm00iMFFhHY2pvsKTdUKcEAuHBVdqBiM3QVFZuTa96sQBtAMaIHMW0xV6KotjXdfU1UDoTPz3G8If2eczXNt19CcYFgfmVnUxOxYgmsHIM+U6JKXGh8UkFoK4Tw9d3fjB3rXZqwsUkHK4A7n8+XZ9E7X5I157Lr/mLHXD9PebzYA5wwujk9PAaK4eI2NvcIh2oDC7kDU/5C+3WzWOYy8N63ChBQ3/qujuLk0ZHllYjISx80LzmSSSHtwSUldWN5IY3nOpoUqYYUdAlh1a3rQouXyRGhfdu38qBb1X8dI2uaULEW4mYRbvP4IY933Nk2Qa7zKW4ynnFdzAphPoufbq7Vxl3ja3hR76AI0xtBHagbJMFsVYWLXyNwz/26D5WI3MAtBw44DcgMn6QH5VWIEtD+qARiZQKyXx1ylR7Mvgru1pMUsJtoTnuXIyXMXOjAkzK04P8iiHVLO1F9dFxqPKAkTEW5EuCnnysleqLo4f9IqsNuKruD576ODTiqCMBeLQOAKAalLLMc+z0uusMC+0an1ipv8LJQ/J7QTC6x/vCz5d7qR7pxGsOg6/k9iKfwYP1iqJYhMz9E4/96P3ML+RbHjzMcHyWY0Uwr08JdDNUef3fBfoFrtX9f9x+CWmImxjzvY=
  provider: lambda
  role: arn:aws:iam::042143839109:role/lambda_execution
  function_name: autismFact
  handler_name: handler
  runtime: nodejs4.3
notifications:
  email: false
  slack:
    secure: siyEUk8Rlra5qpyOwIyjpkawbxUV8sxg4pkJDCXRjiTH5H4kJnDtEEJtkKrYI/WVZcBhEQo9uVG5Il9ITgD3fcYQwZxmPZ9wDXillM56VHU3Y3XDSgdzfaSs0IhTc5JcG0Jm/17oHRQ4OsfZuKVql4gPgysid4nlnFzoFJF5JZNPPoeFylQUWSS412FXXTq0JMww9L2y0NWJaUuq6dC8N4gAE/zyfAW0+JInDdLu+Nidepxe9ZqV9/tdAibl+CCWGfrxtjp6QDITlSNET0ezRdVqy7l7b+DOY/ZxV8VXUiv9k5R53EWwfp687FXqwZWpaSaE7AD9X38SJBQMxMEBYYGeFVzuTnwOILf4E/m4aeXJ8CuHhwO5HLTVHxT9DBl9tNrpM53RVFkeRiGikaV8yKicMGxIueaZ+KyhvHf9NBInU9fyqieaBq8boL/00u4I6wG26lLLYpHCdCE7HRNdk1rgMP3sWDqHVONSCJdu1PQUWs0VpBMvKXiauVsl80eP3N6ErKopY5TVsu4n9o7aqYyRfPiBbflH3zV74XBBtkvoh5gUe7ZhJxN3Rn9hDZnhQh/uQZLOVw4XyI934E5n1/KgGQSHW+uBM1W1OSB7fw/9EIl2zXKwL3hXNWNDhl1TRALcIudMFNAB9vRd2rUEgjXxUdPjatVuG6Psz6BenAQ=
