language: node_js
node_js:
  - "6"

deploy:
  access_key_id: "AKIAIG5K6XQOZJOHOH5A"
  secret_access_key:
    secure: CWcfNkaPK2PDF63rHuRGV5eAZlazkAvCgFuObpRYX5fjLGOd0iSD2GiuhwmPJ3pxLUjMbvutIP2tyi2HM8OwLLfunu2i2FiVKmXZL5D93K/CkiUiHYz3QBAAGyPzl7LIGCosVyftAstrNJoGxq6SmmszXGQWjVQTDx5wEGrD5IF6LPu3Cj02qnVN0Tpz2oJCJOnrdB3iWl+C1c6phtn5053sC1+tds48w6NdzxncfnRyN0/5taWttRHBdtIGeKVi46qMCXzEAFsTX1IqKT3XthEgjPHr9BYe0ZBrkzbJduhbKBGielTPGdORmuLra5gNX1kZZNJt1MZq2AaGVwm7dLmP/wb002i706NHPJMh1XFpp5Y23lreps4goFM0ehCgK0fWKcJx6d3mNsNs97jvz81UI/PK/vynnr4ub+VDzRhyb8ledy1faTLsIsbJKy/LK+h7SuaTl+GWJ5Jv/7/pMJB1EOpn41eft18WzqPRqcyJ+C/Yiegj9XZ2WV7WU6LTL+nwKWA2z5v98dVl4nBp+7a0/+JxTRnS1PbTZ8HqeKBceW7EpN55nlHC9fugAcWkYEilPusm7Y89eNeYjs/xbILQOGibB8q+VtZ0WBmEt+DKJdgDWokUcwPTD/i/huoztjO4Vzj+3VtqtUdcLn12BIRquHiIalQrPJCB2Rx3onI=
  provider: lambda
  role: "arn:aws:iam::287158525228:role/lambda_basic_execution"
  function_name: "myFactSkill"
  handler_name: "index.handler"