language: node_js
node_js:
  - "6"

script:
 - npm test

deploy:
  access_key_id: "AKIAIG5K6XQOZJOHOH5A"
  secret_access_key:
    secure: CWcfNkaPK2PDF63rHuRGV5eAZlazkAvCgFuObpRYX5fjLGOd0iSD2GiuhwmPJ3pxLUjMbvutIP2tyi2HM8OwLLfunu2i2FiVKmXZL5D93K/CkiUiHYz3QBAAGyPzl7LIGCosVyftAstrNJoGxq6SmmszXGQWjVQTDx5wEGrD5IF6LPu3Cj02qnVN0Tpz2oJCJOnrdB3iWl+C1c6phtn5053sC1+tds48w6NdzxncfnRyN0/5taWttRHBdtIGeKVi46qMCXzEAFsTX1IqKT3XthEgjPHr9BYe0ZBrkzbJduhbKBGielTPGdORmuLra5gNX1kZZNJt1MZq2AaGVwm7dLmP/wb002i706NHPJMh1XFpp5Y23lreps4goFM0ehCgK0fWKcJx6d3mNsNs97jvz81UI/PK/vynnr4ub+VDzRhyb8ledy1faTLsIsbJKy/LK+h7SuaTl+GWJ5Jv/7/pMJB1EOpn41eft18WzqPRqcyJ+C/Yiegj9XZ2WV7WU6LTL+nwKWA2z5v98dVl4nBp+7a0/+JxTRnS1PbTZ8HqeKBceW7EpN55nlHC9fugAcWkYEilPusm7Y89eNeYjs/xbILQOGibB8q+VtZ0WBmEt+DKJdgDWokUcwPTD/i/huoztjO4Vzj+3VtqtUdcLn12BIRquHiIalQrPJCB2Rx3onI=
  provider: lambda
  role: "arn:aws:iam::287158525228:role/lambda_basic_execution"
  function_name: "myFactSkill"
  handler_name: "index.handler"

notifications:
  email: false
  slack:
    secure: saT6I5P7ypAArZwDSyC//fejVDHUDaT/8sOZY8qGUXxHA2wXiORYQROUmyLdk+kThhg1vAsPvk+VECBjs/KzvZaehSZmg38XfJuTFb5yp42WbK58x7nHNsmAc4hJPlSSsIUplZ6ORxjbgfvIq1WTyrxpkYmRXztb2BVvDsQphVrPCYO2PwIdfCsvsJ5KoDSL+tcxkm7APkPN3btd9w7HG48fg7tVR7I+vLqt1A6pxvTXtcScn1z/YwvYsEd+3uxIEYe9K1cQvybFxHGVaB8hPjUmhNNptifhBDcJtR8PyG+VXE5qN9ZdvS5cTwIxML0FPx9FF2Ok7ElTfLEkmLXqYMlL57w+bf5RBYTn4GIIoBj6k/PAiephghKC/H+sw5r6yvBQdRCs+/NOM3f5L8F/AFmxrOKfDo4RIjJ+qRfEK7ppfljHBAPOfFgSiYaVcRoxhaw1d3ooiq/XT6AxyTr80Mz8mAB3dUvRCw0gB3/lsbvLKGrSyTp14ERwdfHpcgxpGMMhJu7ketXe6gUrYIIffbNg5ItXg88x//jx5NKdTqZMs/S1yR1/dQPiPkxbZckARIbmTwJK/oTTLaW5fj3WiWsb7sqxx0u+DWZnRvLbqI+LI0X0L/ewRvK9hMmwVXc5jZuzH3fwDpiWEzJxuQiiZyL/9E8DXhbn5Msl77LkAVQ=
  